// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATdi1eVrwd1y54kncdhA_FzM9FZPgnIGc',
    appId: '1:1000990435480:web:1624ba44e04c63fbd608ed',
    messagingSenderId: '1000990435480',
    projectId: 'chord-app-63d1a',
    authDomain: 'chord-app-63d1a.firebaseapp.com',
    storageBucket: 'chord-app-63d1a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwkh2PMv-VmSkaVaxjG4s9KgMqd0WM6bI',
    appId: '1:1000990435480:android:9133f763896b7764d608ed',
    messagingSenderId: '1000990435480',
    projectId: 'chord-app-63d1a',
    storageBucket: 'chord-app-63d1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6tM_Rb9H2kEHddwB94THG31vmEQ_uYu0',
    appId: '1:1000990435480:ios:1a000758be72c9c7d608ed',
    messagingSenderId: '1000990435480',
    projectId: 'chord-app-63d1a',
    storageBucket: 'chord-app-63d1a.firebasestorage.app',
    iosBundleId: 'com.example.mobileappsV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6tM_Rb9H2kEHddwB94THG31vmEQ_uYu0',
    appId: '1:1000990435480:ios:1a000758be72c9c7d608ed',
    messagingSenderId: '1000990435480',
    projectId: 'chord-app-63d1a',
    storageBucket: 'chord-app-63d1a.firebasestorage.app',
    iosBundleId: 'com.example.mobileappsV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATdi1eVrwd1y54kncdhA_FzM9FZPgnIGc',
    appId: '1:1000990435480:web:f968ed4ffd68a407d608ed',
    messagingSenderId: '1000990435480',
    projectId: 'chord-app-63d1a',
    authDomain: 'chord-app-63d1a.firebaseapp.com',
    storageBucket: 'chord-app-63d1a.firebasestorage.app',
  );
}
